### ISSUE TITLE
SemanticKITTI DataLoader -- npz_load: failed fread

### ISSUE THREAD

**Issue by kasparas-k** [RaduAlexandru/data_loaders#2]
Hello,

thank you for your hard work making an extensive library of dataloaders for commonly used datasets.

I've tried using your dataloader for SemanticKITTI and the similarly structured [SemanticPOSS](http://www.poss.pku.edu.cn/semanticposs.html) but I run into the issue when starting the dataloaders.

```
[    6030B740]LabelMngr.cxx:68       1| Read a unabeled idx of 0
LabelMngr: nr of classes read 23
[    6030B740]DataLoaderSemanticKitti.cxx:164      1| full path is "/workspace/data/SemanticPOSS/train/00"
[    6030B740]DataLoaderSemanticKitti.cxx:165      1| sequence is 00
[    6030B740]DataLoaderSemanticKitti.cxx:164      1| full path is "/workspace/data/SemanticPOSS/train/03"
[    6030B740]DataLoaderSemanticKitti.cxx:165      1| sequence is 03
[    6030B740]DataLoaderSemanticKitti.cxx:164      1| full path is "/workspace/data/SemanticPOSS/train/01"
[    6030B740]DataLoaderSemanticKitti.cxx:165      1| sequence is 01
[    6030B740]DataLoaderSemanticKitti.cxx:164      1| full path is "/workspace/data/SemanticPOSS/train/02"
[    6030B740]DataLoaderSemanticKitti.cxx:165      1| sequence is 02
[    6030B740]DataLoaderSemanticKitti.cxx:192      1| m_nr_sequences is 4
About to read 20 clouds
[    6030B740]LabelMngr.cxx:68       1| Read a unabeled idx of 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  npz_load: failed fread

Aborted (core dumped)
```

I have no issues opening the binary files with `np.fromfile(filepath, dtype=np.float32)`

I thought maybe the dataset is the issue, so I downloaded the much larger SemanticKITTI. I'm not sure how to handle remapping of indices for the labels so they can  be used in training, commonly used in other SemanticKITTI loaders, so I might be messing up here. I didn't see any reference to the LabelMngr's files in the reading of the point cloud npz data, so I just reused the same files I made for SemanticPOSS for testing purposes. I got the same npz_load: failed fread error

If it's of any help, these are the label manager files I made for the SemanticPOSS dataset:
```
#color scheme BGR format [0-255]
0, 0, 0                           
0, 0, 0
0, 0, 0
0, 0, 0                              
255, 30, 30              
255, 30, 30            
255, 40, 200           
100, 150, 245          
135,60,0               
0, 175, 0              
255, 0, 0              
255, 0, 0              
255, 0, 0              
255, 240, 150          
125, 255, 0           
255, 200, 0           
50, 255, 255           
255, 120, 50           
0, 0, 0
0, 0, 0
0, 0, 0  
100, 230, 245          
128, 128, 128 
```
```
#frequency as a ratio to the total number of points
0.0                                                                                                                                     
0.0                                                                                                                                     
0.0                                                                                                                                     
0.0                                                                                                                                     
1.0
1.0 
1.0 
1.0
1.0
1.0 
1.0 
1.0
1.0
1.0 
1.0 
1.0
1.0
1.0 
0.0
0.0
0.0
1.0 
1.0
```
(didn't look into what ratio does, my current guess could be that it's used for weighting loss calculations for unbalanced classes, but for now I just set everything to 1 just like in the partnet example file)
```
#label names
unlabeled                                                             
whatever 1
whatever 2
whatever 3
1 person                                                              
2+ person                                                             
rider                                                                
car                                                                  
trunk                                                                
plants                                                                
traffic sign standing                                      
traffic sign hanging                                      
traffic sign big                               
pole                                                                 
trashcan                                                             
building                                                             
cone/stone                                                           
fence     
whatever 4
whatever 5
whatever 6                                                           
bike                                                                 
ground
```

**Comment by RaduAlexandru** [comment]
Hi,

I think the issue here is that the SemanticKitti loader is using an older format of the dataset and I don't think it works anymore. It's one of the oldest loaders that I wrote so it's quite outdated. It assumes that each point cloud is in an npz file containing point of (x,y,z,label).

I think you can find a more updated loader here:
https://github.com/AIS-Bonn/temporal_latticenet/blob/main/dataloader/kitti_dataloader.py
However it was more meant for loading clouds temporally so it might need a bit of configuring in order to load one cloud at a time.

Regarding more info about remapping of indices, you can check on the official api at:
https://github.com/PRBonn/semantic-kitti-api
They provide the mappings necessary for training and the inverse mapping for evaluating.

I hope this helps. I hope soon I can get around to updating the loader for SemanticKitti to work with the current format.
